### ISSUE TITLE
Diff isn't copied on click [specific case]

### ISSUE THREAD

**Issue by babobski** [moshfeu/vscode-diff-merge#29]
When using the merge with clipboard function, it is not inserting the right lines when trying to merge.
It is inserting the wrong lines when trying to merge. I had this once with the normal file to file merge, my best guess is that it has something to do with line ending.

**Comment by moshfeu** [comment]
Thanks!
Is it similar to #27? If so, there is already fix which waiting for approval. I'd love you to test it and let me know.

https://github.com/moshfeu/vscode-diff-merge/issues/27#issuecomment-731635852

**Comment by babobski** [comment]
Thank I will test it, will report back with my findings

**Comment by babobski** [comment]
Just tested, but it still fails. Do you have a email I can sent you some files for testing?

**Comment by moshfeu** [comment]
Sure. moshfeu.dev@gmail.com.
Thanks!

**Comment by moshfeu** [comment]
@babobski I've changed the issue's title to better reflect the actual issue.

**Comment by SilverLinings89** [comment]
I just gave this extension a try because I would like Webstorm-esque diff views and it looks great so far. However, when I want to accept a change and click the arrow, it copies the wrong line. Both versions were still very similar in line-counts and I had just opened the view. Clicking accept in line 165 inserted the content of line 83 on the right side. I ran another test and it copied the wrong line again. Here is a list of attempts I made:

Copy line:  165     Gave    83
Copy line:  145     Gave    73
Copy line:   363    Gave    181

So maybe OP has the same issue but is inserting empty lines from somewhere else in the file. It seems to be some factor 2 and rounding effect.

I hope this helps to fix this weird bug in your otherwise nice extension.

**Comment by moshfeu** [comment]
Hi @SilverLinings89. Thanks for letting me know.
I think that #30 solves this issue (click on the arrow does nothing) and you point to a different one (click on the arrow copy the wrong string).

Can you create a new issue? And if you can also add the files you're trying to compare (in a zip file) this will be even greater. 
Thanks!
