### ISSUE TITLE
GIT merge conflict

### ISSUE THREAD

**Issue by FDiskas** [moshfeu/vscode-diff-merge#58]
Hi, I love the way you go with your plugin.

I have a suggestion to extend this and allow to merge conflicting files also.

Confflicting file: demo.tst
```
Finance team
-Charles
-Lisa
-John
<<<<<<< HEAD
-Stacy
-Alexander

Marketing team
- Collins
- Linda
- Patricia
- Morgan
- Amanda
=======
>>>>>>> master
```

Default "compare" functionality
![image](https://user-images.githubusercontent.com/468006/135331274-a4d570d9-929c-4432-9f4a-330de03bf888.png)

possible conflict edit screen
![image](https://user-images.githubusercontent.com/468006/135331510-7c185159-07ab-4aae-a09d-3eaac0c6b855.png)

**Comment by moshfeu** [comment]
Thank you, interesting idea!

The main challenge is to write the "parser" similar to the `git diff` parser the extension has.
Another challenge is in the UI. Assuming we want to give a context menu to open diff-merge rather than the default one, we need to find out how to determine if it's a conflict file and we should show the context menu.

That's for the technical staff. As the reality, I'd love to work on this feature but unfortunately, I don't have enough time to work on it.
If you'd like to take this, that will be great and I'll try to help as much as I can.

**Comment by FDiskas** [comment]
there is already Extention builtin within vscode - maybe it can be reused

https://github.com/microsoft/vscode/blob/2678e4b848ab2506e2d25bc16985a8b81df79000/extensions/merge-conflict/src/mergeConflictParser.ts

**Comment by moshfeu** [comment]
Interesting. I'm not sure it can be as is because it's not just parsing the file but also adding the UI.
The parsing code can be copied though.
Important step forward! Would you like to take it further and coding it?

**Comment by FDiskas** [comment]
Same :) no time, but maybe but but but :)
Or I'm to lazy 🦥

**Comment by moshfeu** [comment]
😁 Yah. I'll keep that issue maybe I or someone else will have time.
